name: steg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - ujson
  - numpy
  - pip
  - imageio
  - tensorboard
  - tensorflow
  - tensorboardX
  - tqdm
  - urllib3
  - pytorch 
  - cudatoolkit = 10.1.243
  - imageio
  - scikit-learn
  - torchvision
  - pandas
  - scipy
